name: bike_now_flutter
description: BikeNow App with Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  json_serializable: ^3.2.2
  http: ^0.12.0+2
  logging: ^0.11.3+2
  web_socket_channel: ^1.0.15
  provider: ^3.1.0
  google_maps_flutter: ^0.5.21
  shared_preferences: ^0.5.3+4
  rxdart: ^0.22.2
  sqflite: ^1.1.6+4
  path_provider: ^1.3.0
  json_annotation: ^3.0.0
  uuid: ^2.0.2
  xml: ^3.5.0
  geolocator: ^5.1.4+1
#  flutter_background_geolocation: ^1.2.2
#  flutter_local_notifications: ^0.8.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.3
  build_runner: ^1.6.9

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/appIcon/appIcon.png"
  image_path_android: "assets/appIcon/appIcon.png"
  adaptive_icon_background: "assets/appIcon/appIcon.png"
  adaptive_icon_foreground: "assets/appIcon/appIcon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/gpx/HbfToAlbert20kmh.gpx

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

analyser:
  strong-mode: true
  language:
    enableSuperMixins: true
