/// Flutter icons CustomGame
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomGameIcons
///      fonts:
///       - asset: fonts/CustomGameIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

// ignore_for_file: constant_identifier_names
class CustomGameIcons {
  CustomGameIcons._();

  static const _kFontFam = 'CustomGameIcons';
  static const String? _kFontPkg = null;

  static const IconData blank_medal = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blank_trophy = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData distance_medal = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData distance_trophy = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData duration_medal = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData duration_trophy = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData elevation_medal = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData elevation_trophy = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goals = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explore_medal = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explore_trophy = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_medal = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_trophy = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_medal = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_trophy = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
