# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

# Fix for Google Api Errors (https://github.com/fastlane/fastlane/issues/21507#issuecomment-1723116829)
ENV['SUPPLY_UPLOAD_MAX_RETRIES']='5'

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Distribute the build to the internal testers (TU Dresden)."
  lane :internal do
    upload_to_play_store(
      track: 'internal', 
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end

  desc "Distribute the build to the 'Closed Beta' testers."
  lane :closed do
    upload_to_play_store(
      track: 'alpha', # Alpha means "Closed test"
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end

  desc "Distribute the build to the 'Open Beta' testers."
  lane :open do
    upload_to_play_store(
      track: 'beta', # Beta means "Open test"
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end

  desc "Distribute the build to the 'Release'."
  lane :release do
    upload_to_play_store(
      track: 'production', # Production means "Release"
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end
end
