name: Dist / Android / Closed

on:
  push:
    # Every branch that starts with "beta"
    branches:
      - beta*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: self-hosted
    # When upgrading: also upgrade dev.yaml, release.yaml, and test.yaml
    container: ghcr.io/cirruslabs/flutter:3.19.6
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          flutter pub get
          flutter test

  distribute:
    runs-on: self-hosted
    needs: test
    # When upgrading: also upgrade dev.yaml, release.yaml, and test.yaml
    container: ghcr.io/cirruslabs/flutter:3.19.6
    steps:
      - uses: actions/checkout@v2
      - name: Prepare secret files
        run: |
          echo "$GRADLE_PROPERTIES_BASE64" | base64 --decode > android/gradle.properties
          echo "$API_KEY_BASE64" | base64 --decode > android/fastlane/api-key.json
          echo "$KEYSTORE_BASE64" | base64 --decode > android/fastlane/keystore.jks
          echo "$KEY_PROPERTIES_BASE64" | base64 --decode > android/fastlane/key.properties
        env:
          GRADLE_PROPERTIES_BASE64: ${{ secrets.GRADLE_PROPERTIES_BASE64 }}
          API_KEY_BASE64: ${{ secrets.API_KEY_BASE64 }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_PROPERTIES_BASE64: ${{ secrets.KEY_PROPERTIES_BASE64 }}
      - name: Build the Android app bundle
        run: |
          flutter pub get
          flutter build appbundle
      - name: Install Fastlane
        run: |
          gem install fastlane
      - name: Distribute via Fastlane to Closed and Open Track
        run: |
          cd android
          fastlane open
