name: Distribute App to Google Play - Closed Track

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build necessary docker images
        run: docker build -t fastlane -f ${PWD}/Dockerfile.fastlane .
      - name: Run unit tests
        run: docker run --rm -v ${PWD}/.netrc:${HOME}/.netrc -v ${PWD}:/app -w /app cirrusci/flutter:2.10.5 /bin/bash -c "flutter pub get && flutter test"
      - name: Build the Android app bundle
        run: docker run --rm -v ${PWD}/.netrc:${HOME}/.netrc -v ${PWD}:/app -w /app cirrusci/flutter:2.10.5 /bin/bash -c "flutter pub get && flutter build appbundle"
      - name: Distribute via Fastlane
        run: docker run --rm -v ${PWD}:/app -w /app/android fastlane fastlane closed
      - name: Upload the Android app bundle to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/app-release.aab