name: Dist / Android / Internal

on:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: self-hosted
    container: cirrusci/flutter:3.3.7
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          flutter pub get
          flutter test

  distribute:
    runs-on: self-hosted
    needs: test
    container: cirrusci/flutter:3.3.7
    steps:
      - uses: actions/checkout@v2
      - name: Build the Android app bundle
        run: |
          flutter pub get
          flutter build appbundle
      - name: Install Fastlane
        run: |
          gem install fastlane
      - name: Distribute via Fastlane
        run: |
          cd android
          fastlane internal
