name: Dist / Android / Internal

on:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: self-hosted
    # When upgrading: also upgrade dev.yaml, release.yaml, and test.yaml
    container: ghcr.io/cirruslabs/flutter:3.16.9
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          flutter pub get
          flutter test

  distribute:
    runs-on: self-hosted
    needs: test
    # When upgrading: also upgrade dev.yaml, release.yaml, and test.yaml
    container: ghcr.io/cirruslabs/flutter:3.16.9
    steps:
      - uses: actions/checkout@v2
      - name: Build the Android app bundle
        run: |
          flutter pub get
          flutter build appbundle
      - name: Install Fastlane
        run: |
          gem install fastlane
      - name: Distribute via Fastlane
        run: |
          cd android
          fastlane internal
