name: Run Unit Tests

on:
  pull_request:
    branches:
      - dev
      - beta

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build necessary docker images
        run: docker build -t fastlane -f ${PWD}/Dockerfile.fastlane .
      - name: Run unit tests
        run: docker run --rm -v ${PWD}/.netrc:${HOME}/.netrc -v ${PWD}:/app -w /app cirrusci/flutter:2.10.5 /bin/bash -c "flutter pub get && flutter test"