name: Test

on:
  pull_request:
    branches:
      - beta
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: self-hosted
    container: cirrusci/flutter:3.3.7
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests and check for styling errors
        run: |
          flutter pub get
          flutter format --line-length 120 --set-exit-if-changed .
          flutter analyze .
          flutter test
