name: Test

on:
  pull_request:
    branches:
      - beta
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: self-hosted
    container: ghcr.io/cirruslabs/flutter:3.13.2
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests and check for styling errors
        run: |
          flutter pub get
          dart format --line-length 120 --set-exit-if-changed .
          flutter analyze .
          flutter test
